### ISSUE TITLE
copy tags from individual project repos

### ISSUE THREAD

**Issue by warner** [Agoric/SES-beta#1]
We've got full history from the various subprojects, but this repository doesn't have any record of release tags for the subprojects. I didn't see an obvious way to use the `monorepo-tools` to import these, so we might have to walk the original repos manually with `git tag`, find the corresponding commit-id here, and make a new tag with the same value.

Each new tag need to have the project name in it, of course. So where the original `harden` has the `0.0.4` tag on "e84102", the new `SES-shim` repo should have a `harden-0.0.4` tag on 5d364eb3.

I've been in the habit of making GPG signed tags on the packages I've released. I'm ambivalent about whether we should do the same in the monorepo, or leave them unsigned.

**Comment by jfparadis** [comment]
Tags have been added back in December. Closing.
