### ISSUE TITLE
options - naming seems backwards

### ISSUE THREAD

**Issue by kumavis** [Agoric/SES-beta#3]
naming of the options seems backwards. will only tame Date if `noTameDate` is set
https://github.com/Agoric/SES-beta/blob/29b7bfe3690d61d79c2b0a0526a09be377bfb7dd/packages/ses/src/main.js#L90

**Comment by jfparadis** [comment]
@kumavis, thanks!

This was fixed during recent changes to meet the new proposal:
https://github.com/Agoric/SES-beta/commit/bf290e7f36c0db0144b08efb07c5e088136f93f9#diff-1be3ab634aeadac4bb6b3695e68b0fb0R57
